# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - azur-github-action555

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_3cc2a5a16ade4bc8859dc57375068f45 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4317c7d7689f483b99ce633e78f3add3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3cc2a5a16ade4bc8859dc57375068f45 }}/azur_github_action555:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'azur-github-action555'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_73e288325ff54438be339c276a04e751 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3cc2a5a16ade4bc8859dc57375068f45 }}/azur_github_action555:${{ github.sha }}'